### ISSUE TITLE
Frontend/Backend-Stories: One user, One Story.... Multiple Votes!

### ISSUE THREAD

**Issue by radeonxray** [edipetres/HackerNews-GroupF#46] opened 2018-11-09 03:42 UTC
- The user is currently (if fast and quick enough to refresh the page) able to vote on a story created by themself
- The user is able to vote multiple times on the same story!
- If a user has voted on a story, pressing the vote-button on the same story should remove/deduct the vote, not add an additional one.

**Comment by Ekskursantas** [comment] 2018-11-14 23:18
The deduction will be implemented as is in the Hackernews and the way they did is that they have page in their profiles that allow them to remove the unwanted upvotes. As the hannest_id for stories is not generated when posting we can not really refer the creator to the story he created nor the people that upvote. The logic is there, but because the hannest_id is not generated it is not used yet I will close this issue and create a new one that is focused on the generation of hannest_id and link it here. The issue is #53

**Closed by Ekskursantas** 2018-11-14 23:18 UTC
